list: $/pensoft/getinvolved/models/category/columns.yaml
modelClass: Pensoft\GetInvolved\Models\Category
title: Categories
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'pensoft/getinvolved/categories/update/:id'
